### ISSUE TITLE
'Class countries does not exist'

### ISSUE THREAD

**Issue by teeli** [webpatser/laravel-countries#26]
I updated countries package to 1.3.7 and suddenly I can't get a list of countries any more.

Here's my code
```php
<?php namespace Api;

use Illuminate\Support\Facades\Response;
use Webpatser\Countries\CountriesFacade as Countries;

class CountriesController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $countries = Countries::orderBy('name', 'asc')->select('name', 'iso_3166_2 AS code')->get()->toArray();
        return Response::json($countries);
    }

}
```

And here's a full error log:
```
[2015-06-23 15:28:27] dev.ERROR: exception 'ReflectionException' with message 'Class countries does not exist' in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:504
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(504): ReflectionClass->__construct('countries')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(428): Illuminate\Container\Container->build('countries', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(462): Illuminate\Container\Container->make('countries', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\Foundation\Application->make('countries')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(146): Illuminate\Container\Container->offsetGet('countries')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(116): Illuminate\Support\Facades\Facade::resolveFacadeInstance('countries')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(200): Illuminate\Support\Facades\Facade::getFacadeRoot()
#7 /var/www/html/app/controllers/api/CountriesController.php(16): Illuminate\Support\Facades\Facade::__callStatic('orderBy', Array)
#8 /var/www/html/app/controllers/api/CountriesController.php(16): Webpatser\Countries\CountriesFacade::orderBy('name', 'asc')
#9 [internal function]: Api\CountriesController->index()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('index', Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Api\CountriesController), Object(Illuminate\Routing\Route), 'index')
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Api\\CountriesCo...', 'index')
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#26 {main} [] []
```

**Comment by webpatser** [comment]
Don't use the Facade this way. Use the \Webpatser\Countries\Countries class
